### ISSUE TITLE
CipherError

### ISSUE THREAD

**Issue by tkambler** [chrisvel/wreeto_official#38]
Following Docker instructions. Running into errors.

![Screen Shot 2020-07-25 at 10 25 48 PM](https://user-images.githubusercontent.com/4448053/88470740-da071d80-cec5-11ea-9f07-28938f52a0da.png)

**Comment by chrisvel** [comment]
Thank you for opening this issue, it only appears to new installations. 

This happened because of the development to production environment migration last week. So, all you have to do is copy the `RAILS_MASTER_KEY` key and its value from this line https://github.com/chrisvel/wreeto_official/blob/eb9d8220e96751845e48a9f101aa3c32325e1ec6/.env.development.local#L8 to your `.env` file. 

I have added default keys for the installation to get everyone started (for now) and I'll update the readme file with instructions on how to generate new, personal ones. 

Please `docker-compose pull`, try again and let me know.

**Comment by chrisvel** [comment]
@tkambler Did you have any luck ?

**Comment by chrisvel** [comment]
Closing this as it's still pending a reply since August 6th.
